import 'package:flutter/material.dart';

// Control the language of every page (reactive variable)
// Object being monitored for changes
final ValueNotifier<String> globalLanguage = ValueNotifier<String>('zh'); // Initialize

const Map<String, Map<String, String>> textLanguage = {
  'en': {
    'appTitle': 'Healthcare Visit Helper APP',
    'userLogin': 'User Login',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot your password? Reset here',
    'login': 'Login',
    'dontHaveAccount': "Don't have an account? Register here",
    'registerAccount': 'Register Account',
    'register': 'Register',
    'resetPassword': 'Reset Password',
    'enterEmail': 'Enter your email',
    'sendResetLink': 'Send Reset Link',
    'pleaseEnterEmailPassword': 'Please enter both email and password',
    'loginSuccess': 'Login successful!',
    'loginFail': 'Login failed!',
    'pleaseFillAll': 'Please fill in all fields',
    'passwordNotMatch': 'Passwords do not match',
    'registerSuccess': 'Registration successful!',
    'registerFail': 'Registration failed:',
    'resetSent': 'Password reset email sent',
    'resetError': 'Error:',

    // Home Page texts
    'clinicRecommender': 'Clinic Recommendation', // 'Clinic Recommendation System'
    'logOut': 'Logout',
    'confirmLogOut': 'Are you sure you want to log out?',
    'cancel': 'Cancel',
    'selectCity': 'Select your city:',
    'commonSymptoms': 'Common symptoms (multi-select):',
    'inputSymptoms': 'Please describe your symptoms',
    'submitFirst': 'Get Recommendation',
    'submitFollowUp': 'Answer Follow-up',
    'searchFailed': 'Search failed, please try again later.',
    'errorOccurred': 'An error occurred:',
    'taipei': 'Taipei',
    'newTaipei': 'New Taipei',
    'taoyuan': 'Taoyuan',
    'taichung': 'Taichung',
    'tainan': 'Tainan',
    'kaohsiung': 'Kaohsiung',
    'hsinchu': 'Hsinchu',
    'miaoli': 'Miaoli',
    'changhua': 'Changhua',
    'yunlin': 'Yunlin',
    'chiayi': 'Chiayi',
    'pingtung': 'Pingtung',
    'taitung': 'Taitung',
    'hualien': 'Hualien',
    'yilan': 'Yilan',
    'keelung': 'Keelung',
    'nantou': 'Nantou',

    'fever': 'Fever',
    'cough': 'Cough',
    'soreThroat': 'Sore Throat',
    'headache': 'Headache',
    'runnyNose': 'Runny Nose',
    'vomit': 'Vomiting',
    'diarrhea': 'Diarrhea',
    'chestTight': 'Chest Tightness',
    'musclePain': 'Muscle Soreness',
    'fatigue': 'Fatigue'
  },
  'zh': {
    'appTitle': '看診建議APP',
    'userLogin': '使用者登入',
    'email': '電子信箱',
    'password': '密碼',
    'confirmPassword': '確認密碼',
    'forgotPassword': '忘記密碼？在這裡重設',
    'login': '登入',
    'dontHaveAccount': '沒有帳號？點此註冊',
    'registerAccount': '註冊帳號',
    'register': '註冊',
    'resetPassword': '重設密碼',
    'enterEmail': '請輸入電子信箱',
    'sendResetLink': '發送重設連結',
    'pleaseEnterEmailPassword': '請輸入電子信箱與密碼',
    'loginSuccess': '登入成功！',
    'loginFail': '登入失敗！',
    'pleaseFillAll': '請填寫所有欄位',
    'passwordNotMatch': '兩次密碼輸入不一致',
    'registerSuccess': '註冊成功！',
    'registerFail': '註冊失敗：',
    'resetSent': '已寄送密碼重設信',
    'resetError': '錯誤：',

    // Home Page words
    'clinicRecommender': '診所推薦系統',
    'logOut': '登出',
    'confirmLogOut': '您確定要登出嗎？',
    'cancel': '取消',
    'selectCity': '選擇所在縣市：',
    'commonSymptoms': '點選常見症狀（可複選）：',
    'inputSymptoms': '請輸入您的症狀',
    'submitFirst': '推薦診所',
    'submitFollowUp': '回覆問題',
    'searchFailed': '搜尋失敗，請稍後再試。',
    'errorOccurred': '發生錯誤：',

    'taipei': '台北市',
    'newTaipei': '新北市',
    'taoyuan': '桃園市',
    'taichung': '台中市',
    'tainan': '台南市',
    'kaohsiung': '高雄市',
    'hsinchu': '新竹市',
    'miaoli': '苗栗縣',
    'changhua': '彰化縣',
    'yunlin': '雲林縣',
    'chiayi': '嘉義市',
    'pingtung': '屏東縣',
    'taitung': '台東縣',
    'hualien': '花蓮縣',
    'yilan': '宜蘭縣',
    'keelung': '基隆市',
    'nantou': '南投縣',
    'fever': '發燒',
    'cough': '咳嗽',
    'soreThroat': '喉嚨痛',
    'headache': '頭痛',
    'runnyNose': '流鼻水',
    'vomit': '嘔吐',
    'diarrhea': '腹瀉',
    'chestTight': '胸悶',
    'musclePain': '肌肉痠痛',
    'fatigue': '全身無力'
  }
};